<a href="https://colab.research.google.com/github/Dikshuy/hail_UMICaana/blob/master/Untitled0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import cv2
import os
from google.colab import drive
from tensorflow.keras.preprocessing.image import img_to_array
from sklearn.preprocessing import LabelEncoder
from keras.utils import to_categorical
from google.colab.patches import cv2_imshow
drive.mount('/content/drive')
%cd '/content/drive/My Drive/Letters'

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive
/content/drive/My Drive/Letters


In [2]:

symbols = []
alphabets = []

img_path = '/content/drive/My Drive/Letters'
for file in os.listdir('/content/drive/My Drive/Letters'):
  img = cv2.imread(os.path.join(img_path, file))
  _, thresh = cv2.threshold(img, 155, 255, cv2.THRESH_BINARY)
  symbols.append(thresh)

  if file == "C2.jpg":
    alphabets.append("C")
  else:
    alphabets.append(file[0])

encoder = np.array(alphabets)

label_encoder = LabelEncoder()
integer_encoder = label_encoder.fit_transform(encoder)
#print(alphabets)

one_hot = to_categorical(integer_encoder)
#print(one_hot)

data = []
label = []

for j in range(17):
  for i in range(-5, 6):
    rows, cols = symbols[j].shape[:2]
    M = cv2.getRotationMatrix2D((cols/2, rows/2), 3*i, 1)
    res = cv2.warpAffine(symbols[j], M, (rows, cols))
    label.append(one_hot[j])
    #print(one_hot[0][j])
    data.append(res)
    
print(label[70])
#cv2_imshow(data[70]) 
#print(len(label), len(data))

num = len(label)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]


In [3]:
for j in range(num):
  for i in range(1, 11, 2):
    img = data[j]
#    cv2_imshow(img)
#    print(img)
    img1 = cv2.GaussianBlur(img, (i,i), 0)
#    cv2_imshow(img1)
 
    data.append(img1)
    label.append(label[j])
#  cv2_imshow(data[j])
    
#print(len(label), len(data))
#cv2_imshow(data[650])
#print(label[650]) 
#cv2_imshow(data[15])

for j in range(num):
  for i in range(1, 11, 2):
    img2 = cv2.medianBlur(data[j], i)
    data.append(img2)
#    cv2_imshow(img2)
    label.append(label[j])
#  cv2_imshow(data[j])

#print(len(label), len(data))
#print(label[1500])
#cv2_imshow(data[1500])

In [4]:
for j in range(num):
  for i in range(1, 11, 2):
    img3 = cv2.bilateralFilter(data[j], i, 75, 75)
    data.append(img3)
#    cv2_imshow(img3)
    label.append(label[j])
#  cv2_imshow(data[j])
#print(len(label), len(data))
print(label[2379])
#cv2_imshow(data[2379])

[0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]


In [5]:
for j in range(num):
  for i in range(1, 7, 2):
    img5 = cv2.erode(data[j], np.ones((i,i)), iterations = 1)
    data.append(img5)
#    cv2_imshow(img5)
    label.append(label[j])
#  cv2_imshow(img4)
print(label[2500])
#cv2_imshow(data[2500])
#print(len(label), len(data))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]


In [6]:
for j in range(num):
  
  for i in range(1, 7, 2):
    img6 = cv2.dilate(data[j], np.ones((i, i), np.uint8), iterations = 1)
    data.append(img6)
#    cv2_imshow(img6)
    label.append(label[j])
#  cv2_imshow(data[j])
#cv2_imshow(data[3111])
print(label[3111])
#print(len(label), len(data))

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [7]:
for j in range(num):
  
  for i in range(1,7,2):
    img7 = cv2.erode(data[j], np.ones((i, i), np.uint8), iterations =1)
    img7 = cv2.dilate(img7, np.ones((i, i), np.uint8), iterations =1)
    data.append(img7)
#    cv2_imshow(img7)
    label.append(label[j])
#  cv2_imshow(data[j])
#cv2_imshow(data[4112])
#print(label[4112])
#print(len(label), len(data))

In [8]:
for j in range(num):
  data.append(cv2.pyrDown(data[j]))
  label.append(label[j])
  data.append(cv2.pyrUp(data[j]))
  label.append(label[j])

#print(len(label), len(data))


In [9]:
for j in range(num):
  img  = cv2.pyrDown(data[j])
  img = cv2.pyrDown(img)
  img = cv2.pyrUp(img)
  img = cv2.erode(img, np.ones((3, 3), np.uint8), iterations = 1 )
  data.append(img)
  label.append(label[j])

#  cv2_imshow(img)
#print(label[-5])

In [10]:
for i in range(len(data)):
  data[i] = cv2.resize(data[i], (224, 224))
  
#print(data[4000].shape)  

In [20]:
from tensorflow.keras.layers import AveragePooling2D
from tensorflow.keras.layers import Dropout
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Input, ZeroPadding2D
from keras.models import Model

from tensorflow.keras.optimizers import Adam
from sklearn.model_selection import train_test_split
from tensorflow.keras.layers import Conv2D
from tensorflow.keras import Input
data = np.array(data)
label = np.array(label)
print(label.shape)
#print(data[1200].shape)

#X_train, X_test, Y_train, Y_test = train_test_split(data, label, test_size = 0.2, stratify=label, random_state = 1)
#for j in range(1000, 1010):
#  cv2_imshow(X_train[j])
X_train = data
Y_train = label

img1 = cv2.imread('/content/drive/My Drive/C.jpg')
data = []
data.append(img1)
for i in range(len(data)):
  data[i] = cv2.resize(data[i], (224, 224))
data = np.array(data)
X_test = 
X_shape = X_test.shape
X_test = np.reshape(X_test, (1, X_shape[0], X_shape[1], X_shape[2]))

(5236, 17)


In [ ]:
  
#print(data[4000].shape)  

In [21]:
from keras.models import Sequential
from keras.layers import Conv2D, MaxPooling2D 
from keras.layers import Activation, Dropout, Flatten, Dense 
from keras import backend as K 
import keras
model = Sequential() 
model.add(Conv2D(96, (5, 5), strides = (4, 4), padding = 'same',   input_shape = (224, 224, 3))) 
model.add(Activation('relu')) 
model.add(MaxPooling2D(pool_size=(3, 3))) 
  
model.add(Conv2D(256, (5, 5), padding = 'same')) 
model.add(Activation('relu')) 
model.add(MaxPooling2D(pool_size=(2, 2), strides = (2, 2))) 
  
model.add(Conv2D(384, (2, 2),  padding = 'same', activation = 'relu')) 
model.add(Conv2D(384, (2, 2),  padding = 'same', activation = 'relu')) 
model.add(Conv2D(384, (2, 2),  padding = 'same', activation = 'relu')) 
model.add(Activation('relu')) 
model.add(MaxPooling2D(pool_size=(3, 3), strides = (2, 2))) 
  
model.add(Flatten()) 
model.add(Dense(4096)) 
model.add(Activation('relu')) 

model.add(Dense(1028)) 
model.add(Activation('relu')) 
model.add(Dropout(0.5)) 

model.add(Dense(17)) 
model.add(Activation('softmax')) 

model.compile(loss = keras.losses.categorical_crossentropy, optimizer = 'rmsprop', metrics = ['accuracy'])

model.fit(X_train, Y_train, epochs = 2 )


Epoch 1/2
164/164 [==============================] - 299s 2s/step - loss: 19.7110 - accuracy: 0.8100
Epoch 2/2
164/164 [==============================] - 301s 2s/step - loss: 0.5774 - accuracy: 0.9471


In [29]:
Y_test = np.array([0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype = 'float64')
Y_test = np.reshape(Y_test, (1, 17))
score = model.predict((X_test) > 0.5).astype("int32")
print(X_test.shape)

#score = model.predict(X_test)
cv2_imshow(X_test)
print(score)
#print(X_test.shape)
#for i in range( 300, 400):
#  cv2_imshow(X_test[i])

(1, 224, 224, 3)


TypeError: ignored

I need more dataset, handmade dataset. If somebody makes a few images, upload them on github

In [ ]:
"""input_shape = (224, 224, 3)
from keras.layers import Input
X_input = Input(input_shape)
conv1 = Conv2D(96, kernel_size = (11, 11), strides = (4, 4), padding = 'valid', activation = 'relu')(inputs)
max1 = AveragePooling2D(pool_size = (3, 3), strides = (2, 2))(conv1)
conv2 = Conv2D(256, kernel_size = (5, 5), padding = 'same', activation = 'relu')(max1)
max2 = AveragePooling2D(pool_size = (3, 3), strides = (2, 2))(conv2)
print('yayy')
conv3 = Conv2D(384, kernel_size = (3, 3), padding = 'same', activation = 'relu')(max2)
conv4 = Conv2D(384, kernel_size = (3, 3), padding = 'same', activation = 'relu')(conv3)
conv5 = Conv2D(384, kernel_size = (3, 3), padding = 'same', activation = 'relu')(conv4)
max3 = AveragePooling2D(pool_size = (3, 3), strides = (2, 2))(conv5)
print('yayy yayy')
flat = Flatten()(max3)
dense1 = Dense(4096, activation = 'relu')(flat)
dense2 = Dense(1028, activation = 'relu')(dense1)
dense3 = Dense(len(alphabets), activation = 'softmax')(dense2)

model = Model(inputs = X_input, outputs = dense3)

model.compile(loss = keras.losses.categorical_crossentropy, optimizer=Adam, metrics = ['accuracy'])
model.fit(X_train, Y_train, batch_size = 128, epochs = 20)

score = model.evaluate(X_test, Y_test)
print('test_loss', score[0])
print('test_accuracy', score[1])"""

yayy
yayy yayy


ValueError: ignored